#!/bin/sh


GETTEXT="gettext -d timeText_ui"



which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog


	$DIALOG --inputbox "`$GETTEXT \"Enter Continent/City:\"`" 8 35 2> /tmp/input.$$

       	now1=$(export TZ=`cat /tmp/input.$$`;date)
	na=`cat /tmp/input.$$`

	MSG="`$GETTEXT \"Your time is:\"` $now1" 
	#MSG1="`$GETTEXT \"Hello $na, your time now is:\"` \n\n$now1\\n\\n"
		$DIALOG --yesno "$MSG" 7 20 || end
